variable "prefix" {}
variable "container_registry" {}
variable "container_repository" {}
variable "container_image_tag" {}
variable "ram_mib" {}
variable "attach_cloudwatch_policy" {}
variable "attach_ec2_policy" {}
variable "attach_lambda_policy" {}
variable "attach_s3_policy" {}
variable "attach_vpc_policy" {}
variable "eks_cluster_name" {}
